name: documentation

on: 
    push:
        branches:
            - main
        paths:
            - 'docs/**'
            - '.github/workflows/documentation.yml'  # so edits to the workflow itself retrigger
    pull_request:
        branches:
            - main
        paths:
            - 'docs/**'
            - '.github/workflows/documentation.yml'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install your package & dependencies
      run: |
        # install your package so `import xsnap` works
        pip install -e src/
        # install everything your conf.py and autodoc really import
        pip install astropy numpy pandas matplotlib scipy emcee corner

    - name: Install Sphinx and extensions
      run: |
        pip install sphinx sphinx_rtd_theme sphinx_autodoc_typehints sphinx_design myst_parser nbsphinx

    - name: Build docs
      run: |
        sphinx-build docs _build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: > 
        github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        force_orphan: true